### ISSUE TITLE
Amd incompatible?

### ISSUE THREAD

**Issue by losbellos** [shinjiogaki/redqueen#1]
Hej Shinji,

Is this still amd incompatible? I have seen a rebuild withouth Intel libs I run it but it does the same as before, when you compiled to AMD. Same exception.

Instruction set     x86, x86-64, MMX, SSE, SSE2, SSE3, SSE4a
Microarchitecture   AMD K10
Cores   2, 3, 4 or 6

I got the 6 core model.
I read after emails I found that you said:
"thank you. libiomp5md.dll is actually an open mp library. i think now
i can fix the problem :)"

Thanks if you do it.
:-)

BTW congratulation for your workplace, so Arnold will be much faster ha? :-)

**Comment by losbellos** [comment]
Well, I tried to compile but it didnt work, few errors related to the compiler settings I fixed but, then it says error in the code, the first is create rq preview window.  So i give up. I believe i cannot do much about it now.

**Comment by shinjiogaki** [comment]
the current binary doesn't require libiomp5md.dll. probably you can disable the preview window.
i haven't tested on amd cpus but if Zen is really good, i will get one and test with it.

**Comment by losbellos** [comment]
Okay I will try now.

**Comment by losbellos** [comment]
0xc000001d application failed to start correctly

**Comment by losbellos** [comment]
crash dump file. will this help?

<a href=http://www.filedropper.com/redqueenexe7108><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file upload</a></div>

**Comment by losbellos** [comment]
BTW ZEN pushed to 2017...

**Comment by shinjiogaki** [comment]
oh you need AVX.

**Comment by losbellos** [comment]
But it says recompiled without intel libs, isnt that means no AVX need?

**Comment by losbellos** [comment]
I see now so no NO AVX. I dont want to use a bulldozer+ (I mean BAD)  processor. Any other ways? Is it lots of work?
